# Generated by Django 3.0.5 on 2020-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Object viewed', 'verbose_name_plural': 'Objects viewed'},
        ),
        migrations.RemoveField(
            model_name='objectviewed',
            name='user',
        ),
        migrations.AddField(
            model_name='objectviewed',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
